#define IDH_Getting_Started_Introduction 1
#define IDH_Getting_Started_License 2
#define IDH_Getting_Started_Requirements 3
#define IDH_Getting_Started_Installing 4
#define IDH_Getting_Started_Uninstalling 5
#define IDH_Getting_Started_Getting_help 6
#define IDH_File_menu_New 7
#define IDH_File_menu_Open 8
#define IDH_File_menu_Save 9
#define IDH_File_menu_Save_As 10
#define IDH_File_menu_Edit_Text 11
#define IDH_File_menu_Properties 12
#define IDH_File_menu_Print_Setup 13
#define IDH_File_menu_Print_Preview 14
#define IDH_File_menu_Print 15
#define IDH_File_menu_Exit 16
#define IDH_Edit_menu_Undo_Redo 17
#define IDH_Edit_menu_Clipboard 18
#define IDH_Edit_menu_Cut 19
#define IDH_Edit_menu_Copy 20
#define IDH_Edit_menu_Paste 21
#define IDH_Edit_menu_Insert 22
#define IDH_Edit_menu_Delete 23
#define IDH_Edit_menu_Select_All 24
#define IDH_Edit_menu_Rename 25
#define IDH_Edit_menu_Create_Section 26
#define IDH_Edit_menu_Delete_Section 27
#define IDH_Edit_menu_Section_Properties 28
#define IDH_Edit_menu_List_Sections 29
#define IDH_Edit_menu_Options 30
#define IDH_Patch_menu_New_Patch 31
#define IDH_Patch_menu_Open_Patch 32
#define IDH_Patch_menu_Save_Patch 33
#define IDH_Patch_menu_Save_Patch_As 34
#define IDH_Transport_menu_Play_Stop 35
#define IDH_Transport_menu_Pause 36
#define IDH_Transport_menu_Rewind 37
#define IDH_Transport_menu_Repeat 38
#define IDH_Transport_menu_Record 39
#define IDH_Transport_menu_Next_Section 40
#define IDH_Transport_menu_Next_Chord 41
#define IDH_Transport_menu_Previous_Chord 42
#define IDH_Transport_menu_Auto_Rewind 43
#define IDH_MIDI_menu_Devices 44
#define IDH_MIDI_menu_Input 45
#define IDH_MIDI_menu_Output 46
#define IDH_MIDI_menu_Learn 47
#define IDH_MIDI_menu_Assignments 48
#define IDH_MIDI_menu_Note_Mappings 49
#define IDH_MIDI_menu_Chase_Events 50
#define IDH_MIDI_menu_Reset_All_Targets 51
#define IDH_MIDI_menu_Panic 52
#define IDH_View_menu_Toolbar 53
#define IDH_View_menu_Status_bar 54
#define IDH_View_menu_Patch_bar 55
#define IDH_View_menu_Parts_bar 56
#define IDH_View_menu_Piano 57
#define IDH_View_menu_Output_Notes 58
#define IDH_View_menu_Threads 59
#define IDH_View_menu_Record_Player 60
#define IDH_Help_menu_Help_topics 61
#define IDH_Help_menu_ChordEase_on_the_Web 62
#define IDH_Help_menu_Check_for_updates 63
#define IDH_Help_menu_Demo 64
#define IDH_Help_menu_About 65
#define IDH_Options_Chart_Measures_per_line 66
#define IDH_Options_Chart_Font 67
#define IDH_Options_Chart_Default_font 68
#define IDH_Options_Record_Always_record 69
#define IDH_Options_Record_Prompt_for_filename 70
#define IDH_Options_Record_Buffer_size 71
#define IDH_Options_Record_MIDI_file_resolution 72
#define IDH_Options_Record_Output_folder 73
#define IDH_Options_Other_Automatically_check_for_updates 74
#define IDH_Options_Other_Show_tooltips 75
#define IDH_Options_Other_Application_data_folder 76
#define IDH_Loose_ends_Shortcuts 77
