#define IDH_Getting_Started_Introduction 1
#define IDH_Getting_Started_License 2
#define IDH_Getting_Started_Requirements 3
#define IDH_Getting_Started_Installing 4
#define IDH_Getting_Started_Uninstalling 5
#define IDH_Getting_Started_Getting_help 6
#define IDH_File_menu_New 7
#define IDH_File_menu_Open 8
#define IDH_File_menu_Save 9
#define IDH_File_menu_Save_As 10
#define IDH_File_menu_Exit 11
#define IDH_Edit_menu_Undo_Redo 12
#define IDH_Edit_menu_Clipboard 13
#define IDH_Edit_menu_Cut 14
#define IDH_Edit_menu_Copy 15
#define IDH_Edit_menu_Paste 16
#define IDH_Edit_menu_Insert 17
#define IDH_Edit_menu_Delete 18
#define IDH_Transport_menu_Play_Stop 19
#define IDH_Transport_menu_Pause 20
#define IDH_Transport_menu_Rewind 21
#define IDH_Transport_menu_Repeat 22
#define IDH_Transport_menu_Record 23
#define IDH_Transport_menu_Next_Section 24
#define IDH_View_menu_Toolbar 25
#define IDH_View_menu_Status_bar 26
#define IDH_Help_menu_Help_topics 27
#define IDH_Help_menu_ChordEase_on_the_Web 28
#define IDH_Help_menu_Check_for_updates 29
#define IDH_Help_menu_About 30
#define IDH_Loose_ends_Shortcuts 31
