//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ChordEase.rc
//
#define IDR_MAINFRAME                   101
#define IDR_CHORDEASEDOC                102
#define IDR_MIDI_ASSIGNS_CTX            103
#define IDR_MIDI_EVENT_CTX              104
#define IDR_PART_LIST_CTX               105
#define IDR_PATCH                       106
#define IDR_PIANO_CTX                   107
#define IDB_HEADER_SORT                 108
#define IDD_ABOUTBOX                    109
#define IDD_DEVICE                      110
#define IDD_MESSAGE_BOX_CHECK           111
#define IDD_MIDI_ASSIGNS                112
#define IDD_MIDI_EVENT                  113
#define IDD_MIDI_NOTE_MAP               114
#define IDD_MIDI_TARGET_ROW             115
#define IDD_NOTEPAD                     116
#define IDD_OPT_CHART                   117
#define IDD_OPT_OTHER                   118
#define IDD_OPT_RECORD                  119
#define IDD_PART_AUTO                   120
#define IDD_PART_BASS                   121
#define IDD_PART_COMP                   122
#define IDD_PART_INPUT                  123
#define IDD_PART_LEAD                   124
#define IDD_PART_MIDI                   125
#define IDD_PART_OUTPUT                 126
#define IDD_PATCH_GENERAL               127
#define IDD_PATCH_METRONOME             128
#define IDD_PIANO                       129
#define IDD_PROGRESS                    130
#define IDD_ROW_FORM                    131
#define IDD_SPLASH                      132
#define IDD_TABBED                      133
#define IDD_THREADS                     134
#define IDS_APP_ABOUT_TEXT              200
#define IDS_APP_CANT_INIT_COM           201
#define IDS_APP_DEMO_CHECK              202
#define IDS_APP_FOLDER_NOT_FOUND        203
#define IDS_APP_FOLDER_REQUIRED         204
#define IDS_APP_HELP_FILE_MISSING       205
#define IDS_APP_LICENSE                 206
#define IDS_APP_TEMP_FOLDER_NOT_FOUND   207
#define IDS_APP_UNKNOWN_SYSTEM_ERROR    208
#define IDS_CKUP_CANT_GET_ADDR          209
#define IDS_CKUP_CANT_LOAD_DLL          210
#define IDS_CLIPBOARD_CANT_COPY         211
#define IDS_CLIPBOARD_CANT_PASTE        212
#define IDS_COMMON_NO                   213
#define IDS_COMMON_YES                  214
#define IDS_DEVICE_BAR                  215
#define IDS_DEVICE_COL_NAME             216
#define IDS_DEVICE_COL_PORT             217
#define IDS_DEVICE_COL_STATE            218
#define IDS_DEVICE_STATE_CLOSED         219
#define IDS_DEVICE_STATE_OPEN           220
#define IDS_EDIT_REDO_FMT               221
#define IDS_EDIT_UNDO_FMT               222
#define IDS_ENGERR_CANT_CLOSE_MIDI_IN   223
#define IDS_ENGERR_CANT_CLOSE_MIDI_OUT  224
#define IDS_ENGERR_CANT_OPEN_MIDI_IN    225
#define IDS_ENGERR_CANT_OPEN_MIDI_OUT   226
#define IDS_ENGERR_CANT_PLAY_STOPPED    227
#define IDS_ENGERR_CANT_START_MIDI_IN   228
#define IDS_ENGERR_CREATE_TIMER         229
#define IDS_ENGERR_CREATE_TIMER_EVENT   230
#define IDS_ENGERR_CREATE_TIMER_THREAD  231
#define IDS_ENGERR_DESTROY_TIMER        232
#define IDS_ENGERR_DESTROY_TIMER_THREAD 233
#define IDS_ENGERR_RECORDING_TRUNCATED  234
#define IDS_ENGERR_SET_TIMER_RESOLUTION 235
#define IDS_ENGERR_START_TIMER_THREAD   236
#define IDS_ENGERR_STOP_TIMER_THREAD    237
#define IDS_ENGERR_TOO_MANY_NOTES       238
#define IDS_ENGINE_MIDI_DEVICE_NONE     239
#define IDS_ENGMSG_MISSING_DEVICE       240
#define IDS_HLINK_CANT_LAUNCH           241
#define IDS_MIDI_ASS_COL_CHANNEL        242
#define IDS_MIDI_ASS_COL_CONTROL        243
#define IDS_MIDI_ASS_COL_DEVICE         244
#define IDS_MIDI_ASS_COL_EVENT          245
#define IDS_MIDI_ASS_COL_PART           246
#define IDS_MIDI_ASS_COL_PART_NAME      247
#define IDS_MIDI_ASS_COL_PORT           248
#define IDS_MIDI_ASS_COL_TARGET         249
#define IDS_MIDI_EVT_COL_CHANNEL        250
#define IDS_MIDI_EVT_COL_DEVICE         251
#define IDS_MIDI_EVT_COL_MESSAGE        252
#define IDS_MIDI_EVT_COL_P1             253
#define IDS_MIDI_EVT_COL_P2             254
#define IDS_MIDI_EVT_COL_PORT           255
#define IDS_MIDI_EVT_COL_TIMESTAMP      256
#define IDS_MIDI_EVT_PAUSE              257
#define IDS_MIDI_FILE_FILTER            258
#define IDS_MIDI_INPUT_BAR              259
#define IDS_MIDI_NMAP_COL_ENABLE        260
#define IDS_MIDI_NMAP_COL_FUNCTION      261
#define IDS_MIDI_NMAP_COL_IN_CHAN       262
#define IDS_MIDI_NMAP_COL_IN_DEVICE     263
#define IDS_MIDI_NMAP_COL_IN_PORT       264
#define IDS_MIDI_NMAP_COL_OUT_CHAN      265
#define IDS_MIDI_NMAP_COL_OUT_DEVICE    266
#define IDS_MIDI_NMAP_COL_OUT_PORT      267
#define IDS_MIDI_NMAP_COL_PART_INDEX    268
#define IDS_MIDI_NMAP_COL_PART_NAME     269
#define IDS_MIDI_NMAP_COL_ZONE_HIGH     270
#define IDS_MIDI_NMAP_COL_ZONE_LOW      271
#define IDS_MIDI_OUTPUT_BAR             272
#define IDS_MIDI_STAT_ACTIVE_SENSING    273
#define IDS_MIDI_STAT_CHANNEL_WILDCARD  274
#define IDS_MIDI_STAT_CHAN_AFT          275
#define IDS_MIDI_STAT_CLOCK             276
#define IDS_MIDI_STAT_CONTINUE          277
#define IDS_MIDI_STAT_CONTROL           278
#define IDS_MIDI_STAT_EOX               279
#define IDS_MIDI_STAT_KEY_AFT           280
#define IDS_MIDI_STAT_MTC_QTR_FRAME     281
#define IDS_MIDI_STAT_NOTE_OFF          282
#define IDS_MIDI_STAT_NOTE_ON           283
#define IDS_MIDI_STAT_PATCH             284
#define IDS_MIDI_STAT_SONG_POSITION     285
#define IDS_MIDI_STAT_SONG_SELECT       286
#define IDS_MIDI_STAT_START             287
#define IDS_MIDI_STAT_STOP              288
#define IDS_MIDI_STAT_SYSEX             289
#define IDS_MIDI_STAT_SYSTEM_RESET      290
#define IDS_MIDI_STAT_SYSTEM_WILDCARD   291
#define IDS_MIDI_STAT_TUNE_REQUEST      292
#define IDS_MIDI_STAT_WHEEL             293
#define IDS_MIDI_TARG_ROW_CHAN          294
#define IDS_MIDI_TARG_ROW_CONTROL       295
#define IDS_MIDI_TARG_ROW_EVENT         296
#define IDS_MIDI_TARG_ROW_NAME          297
#define IDS_MIDI_TARG_ROW_PORT          298
#define IDS_MIDI_TARG_ROW_RANGE_END     299
#define IDS_MIDI_TARG_ROW_RANGE_START   300
#define IDS_MSGBOX_NO                   301
#define IDS_MSGBOX_YES                  302
#define IDS_MTEVT_CHAN_AFTERTOUCH       303
#define IDS_MTEVT_CONTROL               304
#define IDS_MTEVT_NONE                  305
#define IDS_MTEVT_PROGRAM_CHANGE        306
#define IDS_MTEVT_WHEEL                 307
#define IDS_NOT_APPLICABLE              308
#define IDS_OPTIONS                     309
#define IDS_OPT_OTHER_DATA_FOLDER       310
#define IDS_OPT_REC_OUTPUT_FOLDER       311
#define IDS_OPT_RESET_ALL               312
#define IDS_OPT_RESTORE_DEFAULTS        313
#define IDS_PARTS_BAR                   314
#define IDS_PARTS_COL_FUNCTION          315
#define IDS_PARTS_COL_PART_NAME         316
#define IDS_PARTS_TIP_ENABLE            317
#define IDS_PARTS_TIP_FUNCTION          318
#define IDS_PARTS_TIP_LIST              319
#define IDS_PARTS_TIP_NAME              320
#define IDS_PART_FORMAT                 321
#define IDS_PART_MT_AUTO_PLAY           322
#define IDS_PART_MT_AUTO_VELOCITY       323
#define IDS_PART_MT_AUTO_WINDOW         324
#define IDS_PART_MT_BASS_APPROACH_LENGTH 325
#define IDS_PART_MT_BASS_APPROACH_TRIGGER 326
#define IDS_PART_MT_BASS_SLASH_CHORDS   327
#define IDS_PART_MT_BASS_TARGET_ALIGNMENT 328
#define IDS_PART_MT_COMP_ARP_ORDER      329
#define IDS_PART_MT_COMP_ARP_PERIOD     330
#define IDS_PART_MT_COMP_ARP_PERIOD_QUANT 331
#define IDS_PART_MT_COMP_ARP_REPEAT     332
#define IDS_PART_MT_COMP_VARIATION      333
#define IDS_PART_MT_COMP_VOICING        334
#define IDS_PART_MT_HARM_ANTICIPATION   335
#define IDS_PART_MT_INPUT_TRANSPOSE     336
#define IDS_PART_MT_INPUT_VEL_OFFSET    337
#define IDS_PART_MT_LEAD_HARM_INTERVAL  338
#define IDS_PART_MT_LEAD_HARM_OMIT_MELODY 339
#define IDS_PART_MT_LEAD_HARM_STATIC_MAX 340
#define IDS_PART_MT_LEAD_HARM_STATIC_MIN 341
#define IDS_PART_MT_OUTPUT_PATCH        342
#define IDS_PART_MT_OUTPUT_VOLUME       343
#define IDS_PART_MT_PART_ENABLE         344
#define IDS_PART_MT_PART_FUNCTION       345
#define IDS_PATCH_BAD_FORMAT            346
#define IDS_PATCH_BAR                   347
#define IDS_PATCH_FILTER                348
#define IDS_PATCH_MT_LEAD_IN            349
#define IDS_PATCH_MT_METRO_ENABLE       350
#define IDS_PATCH_MT_METRO_VOLUME       351
#define IDS_PATCH_MT_NEXT_CHORD         352
#define IDS_PATCH_MT_NEXT_SECTION       353
#define IDS_PATCH_MT_PAUSE              354
#define IDS_PATCH_MT_PLAY               355
#define IDS_PATCH_MT_PREV_CHORD         356
#define IDS_PATCH_MT_REPEAT             357
#define IDS_PATCH_MT_REWIND             358
#define IDS_PATCH_MT_SONG_POSITION      359
#define IDS_PATCH_MT_TEMPO              360
#define IDS_PATCH_MT_TEMPO_MULTIPLE     361
#define IDS_PATCH_MT_TRANSPOSE          362
#define IDS_RECORD_AS                   363
#define IDS_RECORD_LOCKED               364
#define IDS_SONG_BAD_METER              365
#define IDS_SONG_ERR_BAD_CHORD          366
#define IDS_SONG_ERR_BAD_CHORD_TYPE     367
#define IDS_SONG_ERR_BAD_COMMAND        368
#define IDS_SONG_ERR_BAD_DURATION       369
#define IDS_SONG_ERR_BAD_KEY            370
#define IDS_SONG_ERR_BAD_MODE           371
#define IDS_SONG_ERR_BAD_ROOT           372
#define IDS_SONG_ERR_BAD_SCALE          373
#define IDS_SONG_ERR_BAD_SYNTAX         374
#define IDS_SONG_ERR_BAD_TEMPO          375
#define IDS_SONG_ERR_CHORD_TONE_RANGE   376
#define IDS_SONG_ERR_DUP_CHORD_TYPE     377
#define IDS_SONG_ERR_READ               378
#define IDS_SONG_ERR_SEC_BAD_REPEAT     379
#define IDS_SONG_ERR_SEC_BAD_SYNTAX     380
#define IDS_SONG_ERR_SEC_CANT_NEST      381
#define IDS_SONG_ERR_SEC_UNTERMINATED   382
#define IDS_THREADS_COL_KERNEL_TIME     383
#define IDS_THREADS_COL_PRIORITY        384
#define IDS_THREADS_COL_THREAD_ID       385
#define IDS_THREADS_COL_USER_TIME       386
#define IDS_UC_BASE_PATCH               387
#define IDS_UC_CUT                      388
#define IDS_UC_DELETE                   389
#define IDS_UC_ENABLE_PART              390
#define IDS_UC_INSERT                   391
#define IDS_UC_MIDI_CHASE               392
#define IDS_UC_MIDI_TARGETS             393
#define IDS_UC_PART                     394
#define IDS_UC_PASTE                    395
#define IDS_UC_RENAME                   396
#define IDS_UC_REORDER                  397
#define IDS_UC_SELECT_PART              398
#define IDS_UC_SELECT_PART_PAGE         399
#define IDS_UC_SELECT_PATCH_PAGE        400
#define IDS_UC_SONG_EDIT                401
#define IDC_ABOUT_LICENSE               1001
#define IDC_ABOUT_TEXT                  1002
#define IDC_ABOUT_URL                   1003
#define IDC_DEVICE_IN_LIST              1004
#define IDC_DEVICE_IN_LIST_CAP          1005
#define IDC_DEVICE_OUT_LIST             1006
#define IDC_DEVICE_OUT_LIST_CAP         1007
#define IDC_DRAG_MULTI                  1008
#define IDC_DRAG_SINGLE                 1009
#define IDC_MIDI_ASSIGNS_LIST           1010
#define IDC_MIDI_EVENT_LIST             1011
#define IDC_MIDI_NOTE_MAP_LIST          1012
#define IDC_MIDI_TARGET                 1013
#define IDC_MIDI_TARG_COL_CHAN          1014
#define IDC_MIDI_TARG_COL_CONTROL       1015
#define IDC_MIDI_TARG_COL_EVENT         1016
#define IDC_MIDI_TARG_COL_NAME          1017
#define IDC_MIDI_TARG_COL_PORT          1018
#define IDC_MIDI_TARG_COL_RANGE_END     1019
#define IDC_MIDI_TARG_COL_RANGE_START   1020
#define IDC_MSGBOXCHK_CHECK             1021
#define IDC_MSGBOXCHK_TEXT              1022
#define IDC_NOTEPAD_EDIT                1023
#define IDC_OPT_CHART_CHOOSE_FONT       1024
#define IDC_OPT_CHART_DEFAULT_FONT      1025
#define IDC_OPT_CHART_LINE_MEASURES     1026
#define IDC_OPT_OTHER_AUTO_CHECK_UPDATES 1027
#define IDC_OPT_OTHER_DATA_FOLDER_BROWSE 1028
#define IDC_OPT_OTHER_DATA_FOLDER_PATH  1029
#define IDC_OPT_OTHER_DATA_FOLDER_TYPE  1030
#define IDC_OPT_OTHER_DATA_FOLDER_TYPE2 1031
#define IDC_OPT_OTHER_SHOW_TOOLTIPS     1032
#define IDC_OPT_REC_ALWAYS_RECORD       1033
#define IDC_OPT_REC_BUFFER_SIZE         1034
#define IDC_OPT_REC_FOLDER_BROWSE       1035
#define IDC_OPT_REC_FOLDER_PATH         1036
#define IDC_OPT_REC_FOLDER_TYPE         1037
#define IDC_OPT_REC_FOLDER_TYPE2        1038
#define IDC_OPT_REC_MIDI_FILE_PPQ       1039
#define IDC_OPT_REC_PROMPT_FILENAME     1040
#define IDC_PARTS_LIST                  1041
#define IDC_PART_AUTO_PLAY              1042
#define IDC_PART_AUTO_VELOCITY          1043
#define IDC_PART_AUTO_WINDOW            1044
#define IDC_PART_BASS_APPROACH_LENGTH   1045
#define IDC_PART_BASS_CHROMATIC         1046
#define IDC_PART_BASS_LOWEST            1047
#define IDC_PART_BASS_SLASH_CHORDS      1048
#define IDC_PART_BASS_TARGET_ALIGNMENT  1049
#define IDC_PART_COMP_ARP_ORDER         1050
#define IDC_PART_COMP_ARP_PERIOD        1051
#define IDC_PART_COMP_ARP_REPEAT        1052
#define IDC_PART_COMP_CHORD_RESETS_ALT  1053
#define IDC_PART_COMP_VARIATION         1054
#define IDC_PART_COMP_VOICING           1055
#define IDC_PART_IN_CHAN                1056
#define IDC_PART_IN_DEVICE_NAME         1057
#define IDC_PART_IN_PORT                1058
#define IDC_PART_IN_TRANSPOSE           1059
#define IDC_PART_IN_VEL_OFFSET          1060
#define IDC_PART_IN_ZONE_HIGH           1061
#define IDC_PART_IN_ZONE_LOW            1062
#define IDC_PART_LEAD_HARM_INTERVAL     1063
#define IDC_PART_LEAD_HARM_OMIT_MELODY  1064
#define IDC_PART_LEAD_HARM_STATIC_MAX   1065
#define IDC_PART_LEAD_HARM_STATIC_MIN   1066
#define IDC_PART_MIDI_ROW               1067
#define IDC_PART_OUT_ANTICIPATION       1068
#define IDC_PART_OUT_CHAN               1069
#define IDC_PART_OUT_CONTROLS_THRU      1070
#define IDC_PART_OUT_DEVICE_NAME        1071
#define IDC_PART_OUT_FIX_HELD_NOTES     1072
#define IDC_PART_OUT_LOCAL_CONTROL      1073
#define IDC_PART_OUT_PATCH              1074
#define IDC_PART_OUT_PORT               1075
#define IDC_PART_OUT_VOLUME             1076
#define IDC_PATCH_AINST_CHANNEL         1077
#define IDC_PATCH_AINST_ENABLE          1078
#define IDC_PATCH_AINST_PATCH           1079
#define IDC_PATCH_AINST_PORT            1080
#define IDC_PATCH_AINST_VELOCITY        1081
#define IDC_PATCH_AINST_VOLUME          1082
#define IDC_PATCH_GEN_KEY               1083
#define IDC_PATCH_GEN_LEAD_IN           1084
#define IDC_PATCH_GEN_PPQ               1085
#define IDC_PATCH_GEN_TEMPO             1086
#define IDC_PATCH_GEN_TEMPO_MULTIPLE    1087
#define IDC_PATCH_GEN_TRANSPOSE         1088
#define IDC_PATCH_METRO_ACCENT_NOTE     1089
#define IDC_PATCH_METRO_ACCENT_SAME_NOTE 1090
#define IDC_PATCH_METRO_ACCENT_VEL      1091
#define IDC_PATCH_METRO_NOTE            1092
#define IDC_PIANO_CHANNEL               1093
#define IDC_PIANO_KEY_COUNT             1094
#define IDC_PIANO_PORT                  1095
#define IDC_PIANO_START_NOTE            1096
#define IDC_PIANO_VELOCITY              1097
#define IDC_PROGRESS                    1098
#define IDC_PROGRESS_PERCENT            1099
#define IDC_SPLASH_ICON                 1100
#define IDC_TABDLG_TAB                  1101
#define IDC_THREADS_LIST                1102
#define ID_APP_CHECK_FOR_UPDATES        32771
#define ID_APP_DEMO                     32772
#define ID_APP_HOME_PAGE                32773
#define ID_EDIT_DELETE_PART             32774
#define ID_EDIT_DESELECT                32775
#define ID_EDIT_INSERT_PART             32776
#define ID_EDIT_OPTIONS                 32777
#define ID_EDIT_RENAME                  32778
#define ID_FILE_EDIT                    32779
#define ID_INDICATOR_KEY                32780
#define ID_INDICATOR_METER              32781
#define ID_INDICATOR_POSITION           32782
#define ID_INDICATOR_RECORD             32783
#define ID_INDICATOR_TEMPO              32784
#define ID_MIDIASS_DELETE               32785
#define ID_MIDI_ASSIGNMENTS             32786
#define ID_MIDI_CHASE_EVENTS            32787
#define ID_MIDI_DEVICES                 32788
#define ID_MIDI_EVENT_CLEAR_HISTORY     32789
#define ID_MIDI_EVENT_PAUSE             32790
#define ID_MIDI_INPUT                   32791
#define ID_MIDI_LEARN                   32792
#define ID_MIDI_NOTE_MAPPINGS           32793
#define ID_MIDI_OUTPUT                  32794
#define ID_MIDI_PANIC                   32795
#define ID_MIDI_RESET_ALL               32796
#define ID_PATCH_MRU_FILE1              32797
#define ID_PATCH_MRU_FILE2              32798
#define ID_PATCH_MRU_FILE3              32799
#define ID_PATCH_MRU_FILE4              32800
#define ID_PATCH_NEW                    32801
#define ID_PATCH_OPEN                   32802
#define ID_PATCH_SAVE                   32803
#define ID_PATCH_SAVE_AS                32804
#define ID_PIANO_KEY_LABEL_TYPE         32805
#define ID_PIANO_KEY_LABEL_TYPE2        32806
#define ID_PIANO_KEY_LABEL_TYPE3        32807
#define ID_PIANO_KEY_LABEL_TYPE4        32808
#define ID_PIANO_KEY_LABEL_TYPE5        32809
#define ID_PIANO_ROTATE_LABELS          32810
#define ID_PIANO_SHOW_OCTAVES           32811
#define ID_PIANO_VERTICAL               32812
#define ID_TRANSPORT_NEXT_CHORD         32813
#define ID_TRANSPORT_NEXT_SECTION       32814
#define ID_TRANSPORT_PAUSE              32815
#define ID_TRANSPORT_PLAY               32816
#define ID_TRANSPORT_PREV_CHORD         32817
#define ID_TRANSPORT_RECORD             32818
#define ID_TRANSPORT_REPEAT             32819
#define ID_TRANSPORT_REWIND             32820
#define ID_VIEW_PARTS                   32821
#define ID_VIEW_PATCH                   32822
#define ID_VIEW_PIANO                   32823
#define ID_VIEW_THREADS                 32824

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                1
#define _APS_NEXT_RESOURCE_VALUE        402
#define _APS_NEXT_COMMAND_VALUE         32825
#define _APS_NEXT_CONTROL_VALUE         1103
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
