//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ChordEase.rc
//
#define IDR_MAINFRAME                   101
#define IDR_CHORDEASEDOC                102
#define IDR_CHORDEASEPATCH              103
#define IDB_HEADER_SORT                 104
#define IDD_ABOUTBOX                    105
#define IDD_DEVICE                      106
#define IDD_DURATION                    107
#define IDD_INSERT_CHORD                108
#define IDD_MESSAGE_BOX_CHECK           109
#define IDD_MIDI_ASSIGNS                110
#define IDD_MIDI_EVENT                  111
#define IDD_MIDI_NOTE_MAP               112
#define IDD_MIDI_TARGET_ROW             113
#define IDD_NOTEPAD                     114
#define IDD_OPT_CHART                   115
#define IDD_OPT_OTHER                   116
#define IDD_OPT_RECORD                  117
#define IDD_PART_AUTO                   118
#define IDD_PART_BASS                   119
#define IDD_PART_COMP                   120
#define IDD_PART_INPUT                  121
#define IDD_PART_LEAD                   122
#define IDD_PART_MIDI                   123
#define IDD_PART_OUTPUT                 124
#define IDD_PATCH_GENERAL               125
#define IDD_PATCH_METRONOME             126
#define IDD_PIANO                       127
#define IDD_PROGRESS                    128
#define IDD_ROW_FORM                    129
#define IDD_SECTION_LIST                130
#define IDD_SECTION_PROPS               131
#define IDD_SONG_PROPS                  132
#define IDD_SPLASH                      133
#define IDD_TABBED                      134
#define IDD_THREADS                     135
#define IDM_CHART_CTX                   136
#define IDM_MIDI_ASSIGNS_CTX            137
#define IDM_MIDI_EVENT_CTX              138
#define IDM_OUTPUT_NOTES_CTX            139
#define IDM_PART_LIST_CTX               140
#define IDM_PIANO_CTX                   141
#define IDS_APP_ABOUT_TEXT              200
#define IDS_APP_CANT_INIT_COM           201
#define IDS_APP_DEMO_CHECK              202
#define IDS_APP_FOLDER_NOT_FOUND        203
#define IDS_APP_FOLDER_REQUIRED         204
#define IDS_APP_HELP_FILE_MISSING       205
#define IDS_APP_LICENSE                 206
#define IDS_APP_TEMP_FOLDER_NOT_FOUND   207
#define IDS_APP_UNKNOWN_SYSTEM_ERROR    208
#define IDS_CHART_CSM_BASS              209
#define IDS_CHART_CSM_DURATION          210
#define IDS_CHART_CSM_ROOT              211
#define IDS_CHART_CSM_TYPE              212
#define IDS_CHART_UC_CHORD_EDIT         213
#define IDS_CHART_UC_CUT                214
#define IDS_CHART_UC_DELETE             215
#define IDS_CHART_UC_INSERT             216
#define IDS_CHART_UC_PASTE              217
#define IDS_CHART_UC_REORDER            218
#define IDS_CHART_UC_SECTION_CREATE     219
#define IDS_CHART_UC_SECTION_DELETE     220
#define IDS_CHART_UC_SECTION_PROPS      221
#define IDS_CHART_UC_SONG_EDIT          222
#define IDS_CHART_UC_SONG_PROPS         223
#define IDS_CHORD_DURATION_OTHER        224
#define IDS_CKUP_CANT_GET_ADDR          225
#define IDS_CKUP_CANT_LOAD_DLL          226
#define IDS_CLIPBOARD_CANT_COPY         227
#define IDS_CLIPBOARD_CANT_PASTE        228
#define IDS_COMMON_NO                   229
#define IDS_COMMON_YES                  230
#define IDS_DEVICE_BAR                  231
#define IDS_DEVICE_COL_NAME             232
#define IDS_DEVICE_COL_PORT             233
#define IDS_DEVICE_COL_STATE            234
#define IDS_DEVICE_STATE_CLOSED         235
#define IDS_DEVICE_STATE_OPEN           236
#define IDS_EDIT_REDO_FMT               237
#define IDS_EDIT_UNDO_FMT               238
#define IDS_ENGERR_CANT_CLOSE_MIDI_IN   239
#define IDS_ENGERR_CANT_CLOSE_MIDI_OUT  240
#define IDS_ENGERR_CANT_OPEN_MIDI_IN    241
#define IDS_ENGERR_CANT_OPEN_MIDI_OUT   242
#define IDS_ENGERR_CANT_PLAY_STOPPED    243
#define IDS_ENGERR_CANT_START_MIDI_IN   244
#define IDS_ENGERR_CREATE_TIMER         245
#define IDS_ENGERR_CREATE_TIMER_EVENT   246
#define IDS_ENGERR_CREATE_TIMER_THREAD  247
#define IDS_ENGERR_DESTROY_TIMER        248
#define IDS_ENGERR_DESTROY_TIMER_THREAD 249
#define IDS_ENGERR_RECORDING_TRUNCATED  250
#define IDS_ENGERR_SET_TIMER_RESOLUTION 251
#define IDS_ENGERR_START_TIMER_THREAD   252
#define IDS_ENGERR_STOP_TIMER_THREAD    253
#define IDS_ENGERR_TOO_MANY_NOTES       254
#define IDS_ENGINE_MIDI_DEVICE_NONE     255
#define IDS_ENGMSG_MISSING_DEVICE       256
#define IDS_HLINK_CANT_LAUNCH           257
#define IDS_INSCH_BASS_ROOT             258
#define IDS_INSCH_SELECT_DURATION       259
#define IDS_MIDI_ASS_COL_CHANNEL        260
#define IDS_MIDI_ASS_COL_CONTROL        261
#define IDS_MIDI_ASS_COL_DEVICE         262
#define IDS_MIDI_ASS_COL_EVENT          263
#define IDS_MIDI_ASS_COL_PART           264
#define IDS_MIDI_ASS_COL_PART_NAME      265
#define IDS_MIDI_ASS_COL_PORT           266
#define IDS_MIDI_ASS_COL_TARGET         267
#define IDS_MIDI_EVT_COL_CHANNEL        268
#define IDS_MIDI_EVT_COL_DEVICE         269
#define IDS_MIDI_EVT_COL_MESSAGE        270
#define IDS_MIDI_EVT_COL_P1             271
#define IDS_MIDI_EVT_COL_P2             272
#define IDS_MIDI_EVT_COL_PORT           273
#define IDS_MIDI_EVT_COL_TIMESTAMP      274
#define IDS_MIDI_EVT_PAUSE              275
#define IDS_MIDI_FILE_FILTER            276
#define IDS_MIDI_INPUT_BAR              277
#define IDS_MIDI_NMAP_COL_ENABLE        278
#define IDS_MIDI_NMAP_COL_FUNCTION      279
#define IDS_MIDI_NMAP_COL_IN_CHAN       280
#define IDS_MIDI_NMAP_COL_IN_DEVICE     281
#define IDS_MIDI_NMAP_COL_IN_PORT       282
#define IDS_MIDI_NMAP_COL_OUT_CHAN      283
#define IDS_MIDI_NMAP_COL_OUT_DEVICE    284
#define IDS_MIDI_NMAP_COL_OUT_PORT      285
#define IDS_MIDI_NMAP_COL_PART_INDEX    286
#define IDS_MIDI_NMAP_COL_PART_NAME     287
#define IDS_MIDI_NMAP_COL_ZONE_HIGH     288
#define IDS_MIDI_NMAP_COL_ZONE_LOW      289
#define IDS_MIDI_OUTPUT_BAR             290
#define IDS_MIDI_STAT_ACTIVE_SENSING    291
#define IDS_MIDI_STAT_CHANNEL_WILDCARD  292
#define IDS_MIDI_STAT_CHAN_AFT          293
#define IDS_MIDI_STAT_CLOCK             294
#define IDS_MIDI_STAT_CONTINUE          295
#define IDS_MIDI_STAT_CONTROL           296
#define IDS_MIDI_STAT_EOX               297
#define IDS_MIDI_STAT_KEY_AFT           298
#define IDS_MIDI_STAT_MTC_QTR_FRAME     299
#define IDS_MIDI_STAT_NOTE_OFF          300
#define IDS_MIDI_STAT_NOTE_ON           301
#define IDS_MIDI_STAT_PATCH             302
#define IDS_MIDI_STAT_SONG_POSITION     303
#define IDS_MIDI_STAT_SONG_SELECT       304
#define IDS_MIDI_STAT_START             305
#define IDS_MIDI_STAT_STOP              306
#define IDS_MIDI_STAT_SYSEX             307
#define IDS_MIDI_STAT_SYSTEM_RESET      308
#define IDS_MIDI_STAT_SYSTEM_WILDCARD   309
#define IDS_MIDI_STAT_TUNE_REQUEST      310
#define IDS_MIDI_STAT_WHEEL             311
#define IDS_MIDI_TARG_ROW_CHAN          312
#define IDS_MIDI_TARG_ROW_CONTROL       313
#define IDS_MIDI_TARG_ROW_EVENT         314
#define IDS_MIDI_TARG_ROW_NAME          315
#define IDS_MIDI_TARG_ROW_PORT          316
#define IDS_MIDI_TARG_ROW_RANGE_END     317
#define IDS_MIDI_TARG_ROW_RANGE_START   318
#define IDS_MSGBOX_NO                   319
#define IDS_MSGBOX_YES                  320
#define IDS_MTEVT_CHAN_AFTERTOUCH       321
#define IDS_MTEVT_CONTROL               322
#define IDS_MTEVT_NONE                  323
#define IDS_MTEVT_PROGRAM_CHANGE        324
#define IDS_MTEVT_WHEEL                 325
#define IDS_NOT_APPLICABLE              326
#define IDS_OPTIONS                     327
#define IDS_OPT_OTHER_DATA_FOLDER       328
#define IDS_OPT_REC_OUTPUT_FOLDER       329
#define IDS_OPT_RESET_ALL               330
#define IDS_OPT_RESTORE_DEFAULTS        331
#define IDS_OUTPUT_NOTES_BAR            332
#define IDS_OUT_NOTES_FILTER_ALL        333
#define IDS_OUT_NOTES_SM_ALL_CHANS      334
#define IDS_OUT_NOTES_SM_ALL_PORTS      335
#define IDS_OUT_NOTES_SM_FILTER_CHAN    336
#define IDS_OUT_NOTES_SM_FILTER_PORT    337
#define IDS_OUT_NOTES_SM_PIANO_SIZE     338
#define IDS_PARTS_BAR                   339
#define IDS_PARTS_COL_FUNCTION          340
#define IDS_PARTS_COL_PART_NAME         341
#define IDS_PARTS_TIP_ENABLE            342
#define IDS_PARTS_TIP_FUNCTION          343
#define IDS_PARTS_TIP_LIST              344
#define IDS_PARTS_TIP_NAME              345
#define IDS_PART_FORMAT                 346
#define IDS_PART_MT_AUTO_PLAY           347
#define IDS_PART_MT_AUTO_VELOCITY       348
#define IDS_PART_MT_AUTO_WINDOW         349
#define IDS_PART_MT_BASS_APPROACH_LENGTH 350
#define IDS_PART_MT_BASS_APPROACH_TRIGGER 351
#define IDS_PART_MT_BASS_SLASH_CHORDS   352
#define IDS_PART_MT_BASS_TARGET_ALIGNMENT 353
#define IDS_PART_MT_COMP_ARP_ORDER      354
#define IDS_PART_MT_COMP_ARP_PERIOD     355
#define IDS_PART_MT_COMP_ARP_PERIOD_QUANT 356
#define IDS_PART_MT_COMP_ARP_REPEAT     357
#define IDS_PART_MT_COMP_VARIATION      358
#define IDS_PART_MT_COMP_VOICING        359
#define IDS_PART_MT_HARM_ANTICIPATION   360
#define IDS_PART_MT_INPUT_TRANSPOSE     361
#define IDS_PART_MT_INPUT_VEL_OFFSET    362
#define IDS_PART_MT_LEAD_HARM_INTERVAL  363
#define IDS_PART_MT_LEAD_HARM_OMIT_MELODY 364
#define IDS_PART_MT_LEAD_HARM_STATIC_MAX 365
#define IDS_PART_MT_LEAD_HARM_STATIC_MIN 366
#define IDS_PART_MT_OUTPUT_PATCH        367
#define IDS_PART_MT_OUTPUT_VOLUME       368
#define IDS_PART_MT_PART_ENABLE         369
#define IDS_PART_MT_PART_FUNCTION       370
#define IDS_PATCH_BAD_FORMAT            371
#define IDS_PATCH_BAR                   372
#define IDS_PATCH_MT_LEAD_IN            373
#define IDS_PATCH_MT_METRO_ENABLE       374
#define IDS_PATCH_MT_METRO_VOLUME       375
#define IDS_PATCH_MT_NEXT_CHORD         376
#define IDS_PATCH_MT_NEXT_SECTION       377
#define IDS_PATCH_MT_PAUSE              378
#define IDS_PATCH_MT_PLAY               379
#define IDS_PATCH_MT_PREV_CHORD         380
#define IDS_PATCH_MT_REPEAT             381
#define IDS_PATCH_MT_REWIND             382
#define IDS_PATCH_MT_SONG_POSITION      383
#define IDS_PATCH_MT_TEMPO              384
#define IDS_PATCH_MT_TEMPO_MULTIPLE     385
#define IDS_PATCH_MT_TRANSPOSE          386
#define IDS_RECORD_AS                   387
#define IDS_RECORD_LOCKED               388
#define IDS_SECTION_NAME_SPACES         389
#define IDS_SEC_LIST_COL_IMPLICIT       390
#define IDS_SEC_LIST_COL_INDEX          391
#define IDS_SEC_LIST_COL_LENGTH         392
#define IDS_SEC_LIST_COL_NAME           393
#define IDS_SEC_LIST_COL_REPEAT         394
#define IDS_SEC_LIST_COL_START          395
#define IDS_SONG_BAD_METER              396
#define IDS_SONG_ERR_BAD_BASS_NOTE      397
#define IDS_SONG_ERR_BAD_CHORD          398
#define IDS_SONG_ERR_BAD_CHORD_TYPE     399
#define IDS_SONG_ERR_BAD_COMMAND        400
#define IDS_SONG_ERR_BAD_DURATION       401
#define IDS_SONG_ERR_BAD_KEY            402
#define IDS_SONG_ERR_BAD_MODE           403
#define IDS_SONG_ERR_BAD_ROOT           404
#define IDS_SONG_ERR_BAD_SCALE          405
#define IDS_SONG_ERR_BAD_SYNTAX         406
#define IDS_SONG_ERR_BAD_TEMPO          407
#define IDS_SONG_ERR_CHORD_TONE_RANGE   408
#define IDS_SONG_ERR_DUP_CHORD_TYPE     409
#define IDS_SONG_ERR_READ               410
#define IDS_SONG_ERR_SEC_BAD_REPEAT     411
#define IDS_SONG_ERR_SEC_BAD_SYNTAX     412
#define IDS_SONG_ERR_SEC_CANT_NEST      413
#define IDS_SONG_ERR_SEC_UNTERMINATED   414
#define IDS_THREADS_COL_KERNEL_TIME     415
#define IDS_THREADS_COL_PRIORITY        416
#define IDS_THREADS_COL_THREAD_ID       417
#define IDS_THREADS_COL_USER_TIME       418
#define IDS_UC_BASE_PATCH               419
#define IDS_UC_CUT                      420
#define IDS_UC_DELETE                   421
#define IDS_UC_ENABLE_PART              422
#define IDS_UC_INSERT                   423
#define IDS_UC_MIDI_CHASE               424
#define IDS_UC_MIDI_TARGETS             425
#define IDS_UC_PART                     426
#define IDS_UC_PASTE                    427
#define IDS_UC_RENAME                   428
#define IDS_UC_REORDER                  429
#define IDS_UC_SELECT_PART              430
#define IDS_UC_SELECT_PART_PAGE         431
#define IDS_UC_SELECT_PATCH_PAGE        432
#define IDS_PART_MT_INPUT_NON_DIATONIC  433
#define IDS_PART_MT_INPUT_NOTE          434
#define IDS_PART_MT_INPUT_ZONE_LOW      435
#define IDS_PART_MT_INPUT_ZONE_HIGH     436
#define IDC_ABOUT_LICENSE               1001
#define IDC_ABOUT_TEXT                  1002
#define IDC_ABOUT_URL                   1003
#define IDC_DEVICE_IN_LIST              1004
#define IDC_DEVICE_IN_LIST_CAP          1005
#define IDC_DEVICE_OUT_LIST             1006
#define IDC_DEVICE_OUT_LIST_CAP         1007
#define IDC_DRAG_MULTI                  1008
#define IDC_DRAG_SINGLE                 1009
#define IDC_DURATION_BEATS_EDIT         1010
#define IDC_DURATION_BEATS_SPIN         1011
#define IDC_INSCH_BASS                  1012
#define IDC_INSCH_BEATS                 1013
#define IDC_INSCH_DURATION_UNIT         1014
#define IDC_INSCH_DURATION_UNIT2        1015
#define IDC_INSCH_INSERT_TYPE           1016
#define IDC_INSCH_INSERT_TYPE2          1017
#define IDC_INSCH_MEASURES              1018
#define IDC_INSCH_ROOT                  1019
#define IDC_INSCH_TYPE                  1020
#define IDC_MIDI_ASSIGNS_LIST           1021
#define IDC_MIDI_EVENT_LIST             1022
#define IDC_MIDI_NOTE_MAP_LIST          1023
#define IDC_MIDI_TARGET                 1024
#define IDC_MIDI_TARG_COL_CHAN          1025
#define IDC_MIDI_TARG_COL_CONTROL       1026
#define IDC_MIDI_TARG_COL_EVENT         1027
#define IDC_MIDI_TARG_COL_NAME          1028
#define IDC_MIDI_TARG_COL_PORT          1029
#define IDC_MIDI_TARG_COL_RANGE_END     1030
#define IDC_MIDI_TARG_COL_RANGE_START   1031
#define IDC_MSGBOXCHK_CHECK             1032
#define IDC_MSGBOXCHK_TEXT              1033
#define IDC_NOTEPAD_EDIT                1034
#define IDC_OPT_CHART_CHOOSE_FONT       1035
#define IDC_OPT_CHART_DEFAULT_FONT      1036
#define IDC_OPT_CHART_LINE_MEASURES     1037
#define IDC_OPT_OTHER_AUTO_CHECK_UPDATES 1038
#define IDC_OPT_OTHER_DATA_FOLDER_BROWSE 1039
#define IDC_OPT_OTHER_DATA_FOLDER_PATH  1040
#define IDC_OPT_OTHER_DATA_FOLDER_TYPE  1041
#define IDC_OPT_OTHER_DATA_FOLDER_TYPE2 1042
#define IDC_OPT_OTHER_SHOW_TOOLTIPS     1043
#define IDC_OPT_REC_ALWAYS_RECORD       1044
#define IDC_OPT_REC_BUFFER_SIZE         1045
#define IDC_OPT_REC_FOLDER_BROWSE       1046
#define IDC_OPT_REC_FOLDER_PATH         1047
#define IDC_OPT_REC_FOLDER_TYPE         1048
#define IDC_OPT_REC_FOLDER_TYPE2        1049
#define IDC_OPT_REC_MIDI_FILE_PPQ       1050
#define IDC_OPT_REC_PROMPT_FILENAME     1051
#define IDC_PARTS_LIST                  1052
#define IDC_PART_AUTO_PLAY              1053
#define IDC_PART_AUTO_VELOCITY          1054
#define IDC_PART_AUTO_WINDOW            1055
#define IDC_PART_BASS_APPROACH_LENGTH   1056
#define IDC_PART_BASS_LOWEST            1057
#define IDC_PART_BASS_SLASH_CHORDS      1058
#define IDC_PART_BASS_TARGET_ALIGNMENT  1059
#define IDC_PART_COMP_ARP_ORDER         1060
#define IDC_PART_COMP_ARP_PERIOD        1061
#define IDC_PART_COMP_ARP_REPEAT        1062
#define IDC_PART_COMP_CHORD_RESETS_ALT  1063
#define IDC_PART_COMP_VARIATION         1064
#define IDC_PART_COMP_VOICING           1065
#define IDC_PART_IN_CHAN                1066
#define IDC_PART_IN_DEVICE_NAME         1067
#define IDC_PART_IN_NON_DIATONIC        1068
#define IDC_PART_IN_PORT                1069
#define IDC_PART_IN_TRANSPOSE           1070
#define IDC_PART_IN_VEL_OFFSET          1071
#define IDC_PART_IN_ZONE_HIGH           1072
#define IDC_PART_IN_ZONE_LOW            1073
#define IDC_PART_LEAD_HARM_INTERVAL     1074
#define IDC_PART_LEAD_HARM_OMIT_MELODY  1075
#define IDC_PART_LEAD_HARM_STATIC_MAX   1076
#define IDC_PART_LEAD_HARM_STATIC_MIN   1077
#define IDC_PART_MIDI_ROW               1078
#define IDC_PART_OUT_ANTICIPATION       1079
#define IDC_PART_OUT_CHAN               1080
#define IDC_PART_OUT_CONTROLS_THRU      1081
#define IDC_PART_OUT_DEVICE_NAME        1082
#define IDC_PART_OUT_FIX_HELD_NOTES     1083
#define IDC_PART_OUT_LOCAL_CONTROL      1084
#define IDC_PART_OUT_PATCH              1085
#define IDC_PART_OUT_PORT               1086
#define IDC_PART_OUT_VOLUME             1087
#define IDC_PATCH_AINST_CHANNEL         1088
#define IDC_PATCH_AINST_ENABLE          1089
#define IDC_PATCH_AINST_PATCH           1090
#define IDC_PATCH_AINST_PORT            1091
#define IDC_PATCH_AINST_VELOCITY        1092
#define IDC_PATCH_AINST_VOLUME          1093
#define IDC_PATCH_GEN_KEY               1094
#define IDC_PATCH_GEN_LEAD_IN           1095
#define IDC_PATCH_GEN_PPQ               1096
#define IDC_PATCH_GEN_TEMPO             1097
#define IDC_PATCH_GEN_TEMPO_MULTIPLE    1098
#define IDC_PATCH_GEN_TRANSPOSE         1099
#define IDC_PATCH_METRO_ACCENT_NOTE     1100
#define IDC_PATCH_METRO_ACCENT_SAME_NOTE 1101
#define IDC_PATCH_METRO_ACCENT_VEL      1102
#define IDC_PATCH_METRO_NOTE            1103
#define IDC_PIANO_CHANNEL               1104
#define IDC_PIANO_KEY_COUNT             1105
#define IDC_PIANO_PORT                  1106
#define IDC_PIANO_START_NOTE            1107
#define IDC_PIANO_VELOCITY              1108
#define IDC_PROGRESS                    1109
#define IDC_PROGRESS_PERCENT            1110
#define IDC_SECTION_LIST                1111
#define IDC_SECTION_PROPS_LENGTH        1112
#define IDC_SECTION_PROPS_NAME          1113
#define IDC_SECTION_PROPS_REPEAT        1114
#define IDC_SECTION_PROPS_START         1115
#define IDC_SONG_PROPS_KEY_SIG          1116
#define IDC_SONG_PROPS_TEMPO            1117
#define IDC_SONG_PROPS_TIME_SIG_DENOM   1118
#define IDC_SONG_PROPS_TIME_SIG_NUMER   1119
#define IDC_SONG_PROPS_TRANSPOSE        1120
#define IDC_SPLASH_ICON                 1121
#define IDC_TABDLG_TAB                  1122
#define IDC_THREADS_LIST                1123
#define ID_APP_CHECK_FOR_UPDATES        32771
#define ID_APP_DEMO                     32772
#define ID_APP_HOME_PAGE                32773
#define ID_EDIT_DELETE                  32774
#define ID_EDIT_INSERT                  32775
#define ID_EDIT_OPTIONS                 32776
#define ID_EDIT_RENAME                  32777
#define ID_EDIT_SECTION_CREATE          32778
#define ID_EDIT_SECTION_DELETE          32779
#define ID_EDIT_SECTION_LIST            32780
#define ID_EDIT_SECTION_PROPS           32781
#define ID_FILE_EDIT                    32782
#define ID_FILE_PROPERTIES              32783
#define ID_INDICATOR_KEY                32784
#define ID_INDICATOR_METER              32785
#define ID_INDICATOR_POSITION           32786
#define ID_INDICATOR_RECORD             32787
#define ID_INDICATOR_TEMPO              32788
#define ID_MIDIASS_DELETE               32789
#define ID_MIDI_ASSIGNMENTS             32790
#define ID_MIDI_CHASE_EVENTS            32791
#define ID_MIDI_DEVICES                 32792
#define ID_MIDI_EVENT_CLEAR_HISTORY     32793
#define ID_MIDI_EVENT_PAUSE             32794
#define ID_MIDI_INPUT                   32795
#define ID_MIDI_LEARN                   32796
#define ID_MIDI_NOTE_MAPPINGS           32797
#define ID_MIDI_OUTPUT                  32798
#define ID_MIDI_PANIC                   32799
#define ID_MIDI_RESET_ALL               32800
#define ID_OUT_NOTES_SHOW_KEY_LABELS    32801
#define ID_OUT_NOTES_SHOW_METRONOME     32802
#define ID_PATCH_MRU_FILE1              32803
#define ID_PATCH_MRU_FILE2              32804
#define ID_PATCH_MRU_FILE3              32805
#define ID_PATCH_MRU_FILE4              32806
#define ID_PATCH_NEW                    32807
#define ID_PATCH_OPEN                   32808
#define ID_PATCH_SAVE                   32809
#define ID_PATCH_SAVE_AS                32810
#define ID_PIANO_KEY_LABEL_TYPE         32811
#define ID_PIANO_KEY_LABEL_TYPE2        32812
#define ID_PIANO_KEY_LABEL_TYPE3        32813
#define ID_PIANO_KEY_LABEL_TYPE4        32814
#define ID_PIANO_KEY_LABEL_TYPE5        32815
#define ID_PIANO_KEY_LABEL_TYPE6        32816
#define ID_PIANO_ROTATE_LABELS          32817
#define ID_PIANO_SHOW_OCTAVES           32818
#define ID_PIANO_VERTICAL               32819
#define ID_TRANSPORT_NEXT_CHORD         32820
#define ID_TRANSPORT_NEXT_SECTION       32821
#define ID_TRANSPORT_PAUSE              32822
#define ID_TRANSPORT_PLAY               32823
#define ID_TRANSPORT_PREV_CHORD         32824
#define ID_TRANSPORT_RECORD             32825
#define ID_TRANSPORT_REPEAT             32826
#define ID_TRANSPORT_REWIND             32827
#define ID_VIEW_OUTPUT_NOTES            32828
#define ID_VIEW_PARTS                   32829
#define ID_VIEW_PATCH                   32830
#define ID_VIEW_PIANO                   32831
#define ID_VIEW_THREADS                 32832

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        433
#define _APS_NEXT_COMMAND_VALUE         32833
#define _APS_NEXT_CONTROL_VALUE         1124
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
