//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ChordEase.rc
//
#define IDR_MAINFRAME                   101
#define IDR_CHORDEASEDOC                102
#define IDR_CHORDEASEPATCH              103
#define IDR_NOTEPAD                     104
#define IDB_HEADER_SORT                 105
#define IDI_REC_PLAY_PAUSE              106
#define IDI_REC_PLAY_PLAY               107
#define IDI_REC_PLAY_STOP               108
#define IDD_ABOUTBOX                    109
#define IDD_CHANGE_LENGTH               110
#define IDD_DEVICE                      111
#define IDD_DURATION                    112
#define IDD_INSERT_CHORD                113
#define IDD_MESSAGE_BOX_CHECK           114
#define IDD_MIDI_ASSIGNS                115
#define IDD_MIDI_EVENT                  116
#define IDD_MIDI_NOTE_MAP               117
#define IDD_NOTEPAD                     118
#define IDD_OPT_CHART                   119
#define IDD_OPT_OTHER                   120
#define IDD_OPT_RECORD                  121
#define IDD_PART_AUTO                   122
#define IDD_PART_BASS                   123
#define IDD_PART_COMP                   124
#define IDD_PART_INPUT                  125
#define IDD_PART_LEAD                   126
#define IDD_PART_MIDI                   127
#define IDD_PART_OUTPUT                 128
#define IDD_PATCH_GENERAL               129
#define IDD_PATCH_METRONOME             130
#define IDD_PATCH_SYNC                  131
#define IDD_PIANO                       132
#define IDD_POSITION                    133
#define IDD_PROGRESS                    134
#define IDD_RECORD_PLAYER               135
#define IDD_SECTION_LIST                136
#define IDD_SECTION_PROPS               137
#define IDD_SONG_PROPS                  138
#define IDD_SPLASH                      139
#define IDD_TABBED                      140
#define IDD_THREADS                     141
#define IDD_TRANSPOSE                   142
#define IDM_CHART_CTX                   143
#define IDM_MIDI_ASSIGNS_CTX            144
#define IDM_MIDI_EVENT_CTX              145
#define IDM_MIDI_TARGET_CTX             146
#define IDM_OUTPUT_NOTES_CTX            147
#define IDM_PART_LIST_CTX               148
#define IDM_PIANO_CTX                   149
#define IDS_APP_ABOUT_TEXT              200
#define IDS_APP_CANT_INIT_COM           201
#define IDS_APP_DEMO_CHECK              202
#define IDS_APP_FOLDER_NOT_FOUND        203
#define IDS_APP_FOLDER_REQUIRED         204
#define IDS_APP_HELP_FILE_MISSING       205
#define IDS_APP_LICENSE                 206
#define IDS_APP_TEMP_FOLDER_NOT_FOUND   207
#define IDS_APP_UNKNOWN_SYSTEM_ERROR    208
#define IDS_CHANGE_TIME_SIGNATURE       209
#define IDS_CHART_CSM_BASS              210
#define IDS_CHART_CSM_DURATION          211
#define IDS_CHART_CSM_ROOT              212
#define IDS_CHART_CSM_TYPE              213
#define IDS_CHART_UC_CHANGE_LENGTH      214
#define IDS_CHART_UC_CHORD_EDIT         215
#define IDS_CHART_UC_CUT                216
#define IDS_CHART_UC_DELETE             217
#define IDS_CHART_UC_INSERT             218
#define IDS_CHART_UC_MULTI_CHORD_EDIT   219
#define IDS_CHART_UC_PASTE              220
#define IDS_CHART_UC_REORDER            221
#define IDS_CHART_UC_SECTION_CREATE     222
#define IDS_CHART_UC_SECTION_DELETE     223
#define IDS_CHART_UC_SECTION_PROPS      224
#define IDS_CHART_UC_SONG_EDIT          225
#define IDS_CHART_UC_SONG_PROPS         226
#define IDS_CHART_UC_TRANSPOSE          227
#define IDS_CHORD_DURATION_OTHER        228
#define IDS_CHORD_DURATION_ROUNDING     229
#define IDS_CHORD_PROPS                 230
#define IDS_CKUP_CANT_GET_ADDR          231
#define IDS_CKUP_CANT_LOAD_DLL          232
#define IDS_CLIPBOARD_CANT_COPY         233
#define IDS_CLIPBOARD_CANT_PASTE        234
#define IDS_COMMON_NO                   235
#define IDS_COMMON_YES                  236
#define IDS_DDV_ABOVE_ZERO              237
#define IDS_DDV_NON_ZERO                238
#define IDS_DEVICE_BAR                  239
#define IDS_DEVICE_COL_NAME             240
#define IDS_DEVICE_COL_PORT             241
#define IDS_DEVICE_COL_STATE            242
#define IDS_DEVICE_STATE_CLOSED         243
#define IDS_DEVICE_STATE_OPEN           244
#define IDS_EDIT_REDO_FMT               245
#define IDS_EDIT_UNDO_FMT               246
#define IDS_ENGERR_CANT_CLOSE_MIDI_IN   247
#define IDS_ENGERR_CANT_CLOSE_MIDI_OUT  248
#define IDS_ENGERR_CANT_OPEN_MIDI_IN    249
#define IDS_ENGERR_CANT_OPEN_MIDI_OUT   250
#define IDS_ENGERR_CANT_PLAY_STOPPED    251
#define IDS_ENGERR_CANT_START_MIDI_IN   252
#define IDS_ENGERR_CREATE_TIMER         253
#define IDS_ENGERR_CREATE_TIMER_EVENT   254
#define IDS_ENGERR_CREATE_TIMER_THREAD  255
#define IDS_ENGERR_DESTROY_TIMER        256
#define IDS_ENGERR_DESTROY_TIMER_THREAD 257
#define IDS_ENGERR_RECORDING_TRUNCATED  258
#define IDS_ENGERR_SET_TIMER_RESOLUTION 259
#define IDS_ENGERR_START_TIMER_THREAD   260
#define IDS_ENGERR_STOP_TIMER_THREAD    261
#define IDS_ENGERR_TOO_MANY_NOTES       262
#define IDS_ENGINE_MIDI_DEVICE_NONE     263
#define IDS_ENGMSG_MISSING_DEVICE       264
#define IDS_HLINK_CANT_LAUNCH           265
#define IDS_INSCH_BASS_ROOT             266
#define IDS_INSCH_SELECT_DURATION       267
#define IDS_MIDI_ASS_COL_CHANNEL        268
#define IDS_MIDI_ASS_COL_CONTROL        269
#define IDS_MIDI_ASS_COL_DEVICE         270
#define IDS_MIDI_ASS_COL_EVENT          271
#define IDS_MIDI_ASS_COL_PART           272
#define IDS_MIDI_ASS_COL_PART_NAME      273
#define IDS_MIDI_ASS_COL_PORT           274
#define IDS_MIDI_ASS_COL_TARGET         275
#define IDS_MIDI_EVT_COL_CHANNEL        276
#define IDS_MIDI_EVT_COL_DEVICE         277
#define IDS_MIDI_EVT_COL_MESSAGE        278
#define IDS_MIDI_EVT_COL_P1             279
#define IDS_MIDI_EVT_COL_P2             280
#define IDS_MIDI_EVT_COL_PORT           281
#define IDS_MIDI_EVT_COL_TIMESTAMP      282
#define IDS_MIDI_EVT_PAUSE              283
#define IDS_MIDI_FILE_FILTER            284
#define IDS_MIDI_INPUT_BAR              285
#define IDS_MIDI_NMAP_COL_ENABLE        286
#define IDS_MIDI_NMAP_COL_FUNCTION      287
#define IDS_MIDI_NMAP_COL_IN_CHAN       288
#define IDS_MIDI_NMAP_COL_IN_DEVICE     289
#define IDS_MIDI_NMAP_COL_IN_PORT       290
#define IDS_MIDI_NMAP_COL_OUT_CHAN      291
#define IDS_MIDI_NMAP_COL_OUT_DEVICE    292
#define IDS_MIDI_NMAP_COL_OUT_PORT      293
#define IDS_MIDI_NMAP_COL_PART_INDEX    294
#define IDS_MIDI_NMAP_COL_PART_NAME     295
#define IDS_MIDI_NMAP_COL_ZONE_HIGH     296
#define IDS_MIDI_NMAP_COL_ZONE_LOW      297
#define IDS_MIDI_OUTPUT_BAR             298
#define IDS_MIDI_RECORDING_FILTER       299
#define IDS_MIDI_REC_BAD_FORMAT         300
#define IDS_MIDI_REC_OUT_OF_ORDER       301
#define IDS_MIDI_STAT_ACTIVE_SENSING    302
#define IDS_MIDI_STAT_CHANNEL_WILDCARD  303
#define IDS_MIDI_STAT_CHAN_AFT          304
#define IDS_MIDI_STAT_CLOCK             305
#define IDS_MIDI_STAT_CONTINUE          306
#define IDS_MIDI_STAT_CONTROL           307
#define IDS_MIDI_STAT_EOX               308
#define IDS_MIDI_STAT_KEY_AFT           309
#define IDS_MIDI_STAT_MTC_QTR_FRAME     310
#define IDS_MIDI_STAT_NOTE_OFF          311
#define IDS_MIDI_STAT_NOTE_ON           312
#define IDS_MIDI_STAT_PATCH             313
#define IDS_MIDI_STAT_SONG_POSITION     314
#define IDS_MIDI_STAT_SONG_SELECT       315
#define IDS_MIDI_STAT_START             316
#define IDS_MIDI_STAT_STOP              317
#define IDS_MIDI_STAT_SYSEX             318
#define IDS_MIDI_STAT_SYSTEM_RESET      319
#define IDS_MIDI_STAT_SYSTEM_WILDCARD   320
#define IDS_MIDI_STAT_TUNE_REQUEST      321
#define IDS_MIDI_STAT_WHEEL             322
#define IDS_MIDI_TARG_COL_CHAN          323
#define IDS_MIDI_TARG_COL_CONTROL       324
#define IDS_MIDI_TARG_COL_EVENT         325
#define IDS_MIDI_TARG_COL_NAME          326
#define IDS_MIDI_TARG_COL_PORT          327
#define IDS_MIDI_TARG_COL_RANGE_END     328
#define IDS_MIDI_TARG_COL_RANGE_START   329
#define IDS_MIDI_TARG_COL_VALUE         330
#define IDS_MSGBOX_NO                   331
#define IDS_MSGBOX_YES                  332
#define IDS_MTEVT_CHAN_AFTERTOUCH       333
#define IDS_MTEVT_CONTROL               334
#define IDS_MTEVT_NONE                  335
#define IDS_MTEVT_PROGRAM_CHANGE        336
#define IDS_MTEVT_WHEEL                 337
#define IDS_NOTEPAD_NOT_FOUND           338
#define IDS_NOT_APPLICABLE              339
#define IDS_OPTIONS                     340
#define IDS_OPT_OTHER_DATA_FOLDER       341
#define IDS_OPT_REC_OUTPUT_FOLDER       342
#define IDS_OPT_RESET_ALL               343
#define IDS_OPT_RESTORE_DEFAULTS        344
#define IDS_OUTPUT_NOTES_BAR            345
#define IDS_OUT_NOTES_FILTER_ALL        346
#define IDS_OUT_NOTES_SM_ALL_CHANS      347
#define IDS_OUT_NOTES_SM_ALL_PORTS      348
#define IDS_OUT_NOTES_SM_FILTER_CHAN    349
#define IDS_OUT_NOTES_SM_FILTER_PORT    350
#define IDS_OUT_NOTES_SM_PIANO_SIZE     351
#define IDS_PARTS_BAR                   352
#define IDS_PARTS_COL_FUNCTION          353
#define IDS_PARTS_COL_PART_NAME         354
#define IDS_PARTS_TIP_LIST              355
#define IDS_PART_FORMAT                 356
#define IDS_PART_MT_AUTO_PLAY           357
#define IDS_PART_MT_AUTO_VELOCITY       358
#define IDS_PART_MT_AUTO_WINDOW         359
#define IDS_PART_MT_BASS_APPROACH_LENGTH 360
#define IDS_PART_MT_BASS_APPROACH_TRIGGER 361
#define IDS_PART_MT_BASS_SLASH_CHORDS   362
#define IDS_PART_MT_BASS_TARGET_ALIGNMENT 363
#define IDS_PART_MT_COMP_ARP_ORDER      364
#define IDS_PART_MT_COMP_ARP_PERIOD     365
#define IDS_PART_MT_COMP_ARP_PERIOD_QUANT 366
#define IDS_PART_MT_COMP_ARP_REPEAT     367
#define IDS_PART_MT_COMP_VARIATION      368
#define IDS_PART_MT_COMP_VOICING        369
#define IDS_PART_MT_ENABLE              370
#define IDS_PART_MT_FUNCTION            371
#define IDS_PART_MT_IN_CC_NOTE          372
#define IDS_PART_MT_IN_CC_NOTE_VEL      373
#define IDS_PART_MT_IN_NON_DIATONIC     374
#define IDS_PART_MT_IN_TRANSPOSE        375
#define IDS_PART_MT_IN_VEL_OFFSET       376
#define IDS_PART_MT_IN_ZONE_HIGH        377
#define IDS_PART_MT_IN_ZONE_LOW         378
#define IDS_PART_MT_LEAD_HARM_INTERVAL  379
#define IDS_PART_MT_LEAD_HARM_OMIT_MELODY 380
#define IDS_PART_MT_LEAD_HARM_STATIC_MAX 381
#define IDS_PART_MT_LEAD_HARM_STATIC_MIN 382
#define IDS_PART_MT_OUT_ANTICIPATION    383
#define IDS_PART_MT_OUT_FIX_HELD_NOTES  384
#define IDS_PART_MT_OUT_PATCH           385
#define IDS_PART_MT_OUT_VOLUME          386
#define IDS_PATCH_BAD_FORMAT            387
#define IDS_PATCH_BAR                   388
#define IDS_PATCH_MT_LEAD_IN            389
#define IDS_PATCH_MT_METRO_ENABLE       390
#define IDS_PATCH_MT_METRO_VOLUME       391
#define IDS_PATCH_MT_NEXT_CHORD         392
#define IDS_PATCH_MT_NEXT_SECTION       393
#define IDS_PATCH_MT_PAUSE              394
#define IDS_PATCH_MT_PLAY               395
#define IDS_PATCH_MT_PREV_CHORD         396
#define IDS_PATCH_MT_REPEAT             397
#define IDS_PATCH_MT_REWIND             398
#define IDS_PATCH_MT_SONG_POSITION      399
#define IDS_PATCH_MT_TEMPO              400
#define IDS_PATCH_MT_TEMPO_MULTIPLE     401
#define IDS_PATCH_MT_TRANSPOSE          402
#define IDS_PATCH_PPQ_CHANGE_WARN       403
#define IDS_RECORD_AS                   404
#define IDS_RECORD_LOCKED               405
#define IDS_REC_PLAY_COL_CHANNEL        406
#define IDS_REC_PLAY_COL_DEVICE         407
#define IDS_REC_PLAY_COL_EVENTS         408
#define IDS_REC_PLAY_COL_NAME           409
#define IDS_REC_PLAY_COL_PORT           410
#define IDS_REC_PLAY_STOP_PLAYING       411
#define IDS_REC_PLAY_STOP_RECORDING     412
#define IDS_SECTION_NAME_SPACES         413
#define IDS_SEC_LIST_COL_IMPLICIT       414
#define IDS_SEC_LIST_COL_INDEX          415
#define IDS_SEC_LIST_COL_LENGTH         416
#define IDS_SEC_LIST_COL_NAME           417
#define IDS_SEC_LIST_COL_REPEAT         418
#define IDS_SEC_LIST_COL_START          419
#define IDS_SONG_ERR_BAD_BASS_NOTE      420
#define IDS_SONG_ERR_BAD_CHORD          421
#define IDS_SONG_ERR_BAD_CHORD_TYPE     422
#define IDS_SONG_ERR_BAD_COMMAND        423
#define IDS_SONG_ERR_BAD_DURATION       424
#define IDS_SONG_ERR_BAD_KEY            425
#define IDS_SONG_ERR_BAD_METER          426
#define IDS_SONG_ERR_BAD_MODE           427
#define IDS_SONG_ERR_BAD_ROOT           428
#define IDS_SONG_ERR_BAD_SCALE          429
#define IDS_SONG_ERR_BAD_SYNTAX         430
#define IDS_SONG_ERR_BAD_TEMPO          431
#define IDS_SONG_ERR_CHORD_TONE_RANGE   432
#define IDS_SONG_ERR_DUP_CHORD_TYPE     433
#define IDS_SONG_ERR_READ               434
#define IDS_SONG_ERR_SEC_BAD_REPEAT     435
#define IDS_SONG_ERR_SEC_BAD_SYNTAX     436
#define IDS_SONG_ERR_SEC_CANT_NEST      437
#define IDS_SONG_ERR_SEC_UNTERMINATED   438
#define IDS_SONG_FILTER                 439
#define IDS_THREADS_COL_KERNEL_TIME     440
#define IDS_THREADS_COL_PRIORITY        441
#define IDS_THREADS_COL_THREAD_ID       442
#define IDS_THREADS_COL_USER_TIME       443
#define IDS_UC_BASE_PATCH               444
#define IDS_UC_CUT                      445
#define IDS_UC_DELETE                   446
#define IDS_UC_ENABLE_PART              447
#define IDS_UC_INSERT                   448
#define IDS_UC_MIDI_CHASE               449
#define IDS_UC_MIDI_TARGETS             450
#define IDS_UC_PART                     451
#define IDS_UC_PASTE                    452
#define IDS_UC_RENAME                   453
#define IDS_UC_REORDER                  454
#define IDS_UC_SELECT_PART              455
#define IDS_UC_SELECT_PART_PAGE         456
#define IDS_UC_SELECT_PATCH_PAGE        457
#define IDC_ABOUT_LICENSE               1001
#define IDC_ABOUT_TEXT                  1002
#define IDC_ABOUT_URL                   1003
#define IDC_CHANGE_LENGTH_EDIT          1004
#define IDC_DEVICE_IN_LIST              1005
#define IDC_DEVICE_IN_LIST_CAP          1006
#define IDC_DEVICE_OUT_LIST             1007
#define IDC_DEVICE_OUT_LIST_CAP         1008
#define IDC_DRAG_MULTI                  1009
#define IDC_DRAG_SINGLE                 1010
#define IDC_DURATION_BEATS_EDIT         1011
#define IDC_DURATION_BEATS_SPIN         1012
#define IDC_INSCH_BASS                  1013
#define IDC_INSCH_BEATS                 1014
#define IDC_INSCH_DURATION_UNIT         1015
#define IDC_INSCH_DURATION_UNIT2        1016
#define IDC_INSCH_INSERT_TYPE           1017
#define IDC_INSCH_INSERT_TYPE2          1018
#define IDC_INSCH_INSERT_TYPE_GROUP     1019
#define IDC_INSCH_MEASURES              1020
#define IDC_INSCH_ROOT                  1021
#define IDC_INSCH_TYPE                  1022
#define IDC_MIDI_ASSIGNS_LIST           1023
#define IDC_MIDI_EVENT_LIST             1024
#define IDC_MIDI_NOTE_MAP_LIST          1025
#define IDC_MIDI_TARGET_LIST            1026
#define IDC_MIDI_TARG_CHAN              1027
#define IDC_MIDI_TARG_CONTROL           1028
#define IDC_MIDI_TARG_EVENT             1029
#define IDC_MIDI_TARG_NAME              1030
#define IDC_MIDI_TARG_PORT              1031
#define IDC_MIDI_TARG_RANGE_END         1032
#define IDC_MIDI_TARG_RANGE_START       1033
#define IDC_MIDI_TARG_VALUE             1034
#define IDC_MSGBOXCHK_CHECK             1035
#define IDC_MSGBOXCHK_TEXT              1036
#define IDC_NOTEPAD_EDIT                1037
#define IDC_NOTEPAD_FIND                1038
#define IDC_NOTEPAD_REPLACE             1039
#define IDC_OPT_CHART_CHOOSE_FONT       1040
#define IDC_OPT_CHART_DEFAULT_FONT      1041
#define IDC_OPT_CHART_LINE_MEASURES     1042
#define IDC_OPT_OTHER_AUTO_CHECK_UPDATES 1043
#define IDC_OPT_OTHER_DATA_FOLDER_BROWSE 1044
#define IDC_OPT_OTHER_DATA_FOLDER_PATH  1045
#define IDC_OPT_OTHER_DATA_FOLDER_TYPE  1046
#define IDC_OPT_OTHER_DATA_FOLDER_TYPE2 1047
#define IDC_OPT_OTHER_SHOW_TOOLTIPS     1048
#define IDC_OPT_REC_ALWAYS_RECORD       1049
#define IDC_OPT_REC_BUFFER_SIZE         1050
#define IDC_OPT_REC_FOLDER_BROWSE       1051
#define IDC_OPT_REC_FOLDER_PATH         1052
#define IDC_OPT_REC_FOLDER_TYPE         1053
#define IDC_OPT_REC_FOLDER_TYPE2        1054
#define IDC_OPT_REC_MIDI_FILE_PPQ       1055
#define IDC_OPT_REC_PROMPT_FILENAME     1056
#define IDC_PARTS_LIST                  1057
#define IDC_PART_AUTO_PLAY              1058
#define IDC_PART_AUTO_VELOCITY          1059
#define IDC_PART_AUTO_WINDOW            1060
#define IDC_PART_BASS_APPROACH_LENGTH   1061
#define IDC_PART_BASS_APPROACH_TRIGGER  1062
#define IDC_PART_BASS_LOWEST            1063
#define IDC_PART_BASS_SLASH_CHORDS      1064
#define IDC_PART_BASS_TARGET_ALIGNMENT  1065
#define IDC_PART_COMP_ARP_ORDER         1066
#define IDC_PART_COMP_ARP_PERIOD        1067
#define IDC_PART_COMP_ARP_PERIOD_QUANT  1068
#define IDC_PART_COMP_ARP_REPEAT        1069
#define IDC_PART_COMP_CHORD_RESETS_ALT  1070
#define IDC_PART_COMP_VARIATION         1071
#define IDC_PART_COMP_VOICING           1072
#define IDC_PART_ENABLE                 1073
#define IDC_PART_FUNCTION               1074
#define IDC_PART_IN_CC_NOTE             1075
#define IDC_PART_IN_CC_NOTE_VEL         1076
#define IDC_PART_IN_CHAN                1077
#define IDC_PART_IN_DEVICE_NAME         1078
#define IDC_PART_IN_NON_DIATONIC        1079
#define IDC_PART_IN_PORT                1080
#define IDC_PART_IN_TRANSPOSE           1081
#define IDC_PART_IN_VEL_OFFSET          1082
#define IDC_PART_IN_ZONE_HIGH           1083
#define IDC_PART_IN_ZONE_LOW            1084
#define IDC_PART_LEAD_HARM_INTERVAL     1085
#define IDC_PART_LEAD_HARM_OMIT_MELODY  1086
#define IDC_PART_LEAD_HARM_STATIC_MAX   1087
#define IDC_PART_LEAD_HARM_STATIC_MIN   1088
#define IDC_PART_NAME                   1089
#define IDC_PART_OUT_ANTICIPATION       1090
#define IDC_PART_OUT_CHAN               1091
#define IDC_PART_OUT_CONTROLS_THRU      1092
#define IDC_PART_OUT_DEVICE_NAME        1093
#define IDC_PART_OUT_FIX_HELD_NOTES     1094
#define IDC_PART_OUT_LOCAL_CONTROL      1095
#define IDC_PART_OUT_PATCH              1096
#define IDC_PART_OUT_PORT               1097
#define IDC_PART_OUT_VOLUME             1098
#define IDC_PATCH_GEN_KEY               1099
#define IDC_PATCH_GEN_LEAD_IN           1100
#define IDC_PATCH_GEN_PPQ               1101
#define IDC_PATCH_GEN_TEMPO             1102
#define IDC_PATCH_GEN_TEMPO_MULTIPLE    1103
#define IDC_PATCH_GEN_TRANSPOSE         1104
#define IDC_PATCH_METRO_ACCENT_NOTE     1105
#define IDC_PATCH_METRO_ACCENT_SAME_NOTE 1106
#define IDC_PATCH_METRO_ACCENT_VEL      1107
#define IDC_PATCH_METRO_CHANNEL         1108
#define IDC_PATCH_METRO_DEVICE_NAME     1109
#define IDC_PATCH_METRO_ENABLE          1110
#define IDC_PATCH_METRO_NOTE            1111
#define IDC_PATCH_METRO_PATCH           1112
#define IDC_PATCH_METRO_PORT            1113
#define IDC_PATCH_METRO_VELOCITY        1114
#define IDC_PATCH_METRO_VOLUME          1115
#define IDC_PATCH_SYNC_IN_DEVICE_NAME   1116
#define IDC_PATCH_SYNC_IN_ENABLE        1117
#define IDC_PATCH_SYNC_IN_PORT          1118
#define IDC_PATCH_SYNC_OUT_DEVICE_NAME  1119
#define IDC_PATCH_SYNC_OUT_ENABLE       1120
#define IDC_PATCH_SYNC_OUT_PORT         1121
#define IDC_PIANO_CHANNEL               1122
#define IDC_PIANO_KEY_COUNT             1123
#define IDC_PIANO_PORT                  1124
#define IDC_PIANO_START_NOTE            1125
#define IDC_PIANO_VELOCITY              1126
#define IDC_POSITION_EDIT               1127
#define IDC_PROGRESS                    1128
#define IDC_PROGRESS_PERCENT            1129
#define IDC_REC_PLAY_DURATION           1130
#define IDC_REC_PLAY_EXPORT             1131
#define IDC_REC_PLAY_OPEN               1132
#define IDC_REC_PLAY_PLAY               1133
#define IDC_REC_PLAY_POSITION           1134
#define IDC_REC_PLAY_POS_SLIDER         1135
#define IDC_REC_PLAY_SAVE               1136
#define IDC_REC_PLAY_STOP               1137
#define IDC_REC_PLAY_TITLE              1138
#define IDC_REC_PLAY_TRACK_LIST         1139
#define IDC_SECTION_LIST                1140
#define IDC_SECTION_PROPS_LENGTH        1141
#define IDC_SECTION_PROPS_NAME          1142
#define IDC_SECTION_PROPS_REPEAT        1143
#define IDC_SECTION_PROPS_START         1144
#define IDC_SONG_PROPS_COMMENTS         1145
#define IDC_SONG_PROPS_KEY_SIG          1146
#define IDC_SONG_PROPS_TEMPO            1147
#define IDC_SONG_PROPS_TIME_SIG_DENOM   1148
#define IDC_SONG_PROPS_TIME_SIG_NUMER   1149
#define IDC_SONG_PROPS_TRANSPOSE        1150
#define IDC_SPLASH_ICON                 1151
#define IDC_TABDLG_TAB                  1152
#define IDC_THREADS_LIST                1153
#define IDC_TRANSPOSE_STEPS_EDIT        1154
#define IDC_TRANSPOSE_STEPS_SPIN        1155
#define ID_APP_CHECK_FOR_UPDATES        32771
#define ID_APP_DEMO                     32772
#define ID_APP_HOME_PAGE                32773
#define ID_EDIT_CHORD_PROPS             32774
#define ID_EDIT_DELETE                  32775
#define ID_EDIT_INSERT                  32776
#define ID_EDIT_LENGTH                  32777
#define ID_EDIT_OPTIONS                 32778
#define ID_EDIT_RENAME                  32779
#define ID_EDIT_SECTION_CREATE          32780
#define ID_EDIT_SECTION_DELETE          32781
#define ID_EDIT_SECTION_LIST            32782
#define ID_EDIT_SECTION_PROPS           32783
#define ID_EDIT_TRANSPOSE               32784
#define ID_FILE_EDIT                    32785
#define ID_FILE_PROPERTIES              32786
#define ID_INDICATOR_KEY                32787
#define ID_INDICATOR_METER              32788
#define ID_INDICATOR_POSITION           32789
#define ID_INDICATOR_RECORD             32790
#define ID_INDICATOR_TEMPO              32791
#define ID_MIDIASS_DELETE               32792
#define ID_MIDI_ASSIGNMENTS             32793
#define ID_MIDI_CHASE_EVENTS            32794
#define ID_MIDI_DEVICES                 32795
#define ID_MIDI_EVENT_CLEAR_HISTORY     32796
#define ID_MIDI_EVENT_PAUSE             32797
#define ID_MIDI_EVENT_RESET_FILTERS     32798
#define ID_MIDI_EVENT_SHOW_CTRLR_NAMES  32799
#define ID_MIDI_INPUT                   32800
#define ID_MIDI_LEARN                   32801
#define ID_MIDI_NOTE_MAPPINGS           32802
#define ID_MIDI_OUTPUT                  32803
#define ID_MIDI_PANIC                   32804
#define ID_MIDI_RESET_ALL               32805
#define ID_MIDI_TARGET_RESET            32806
#define ID_OUT_NOTES_ROTATE_LABELS      32807
#define ID_OUT_NOTES_SHOW_KEY_LABELS    32808
#define ID_OUT_NOTES_SHOW_METRONOME     32809
#define ID_PATCH_MRU_FILE1              32810
#define ID_PATCH_MRU_FILE2              32811
#define ID_PATCH_MRU_FILE3              32812
#define ID_PATCH_MRU_FILE4              32813
#define ID_PATCH_NEW                    32814
#define ID_PATCH_OPEN                   32815
#define ID_PATCH_SAVE                   32816
#define ID_PATCH_SAVE_AS                32817
#define ID_PIANO_KEY_LABEL_TYPE         32818
#define ID_PIANO_KEY_LABEL_TYPE2        32819
#define ID_PIANO_KEY_LABEL_TYPE3        32820
#define ID_PIANO_KEY_LABEL_TYPE4        32821
#define ID_PIANO_KEY_LABEL_TYPE5        32822
#define ID_PIANO_KEY_LABEL_TYPE6        32823
#define ID_PIANO_ROTATE_LABELS          32824
#define ID_PIANO_SHOW_OCTAVES           32825
#define ID_PIANO_VERTICAL               32826
#define ID_TRANSPORT_AUTO_REWIND        32827
#define ID_TRANSPORT_GO_TO              32828
#define ID_TRANSPORT_NEXT_CHORD         32829
#define ID_TRANSPORT_NEXT_SECTION       32830
#define ID_TRANSPORT_PAUSE              32831
#define ID_TRANSPORT_PLAY               32832
#define ID_TRANSPORT_PREV_CHORD         32833
#define ID_TRANSPORT_RECORD             32834
#define ID_TRANSPORT_REPEAT             32835
#define ID_TRANSPORT_REWIND             32836
#define ID_VIEW_OUTPUT_NOTES            32837
#define ID_VIEW_PARTS                   32838
#define ID_VIEW_PATCH                   32839
#define ID_VIEW_PIANO                   32840
#define ID_VIEW_RECORD_PLAYER           32841
#define ID_VIEW_THREADS                 32842

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                1
#define _APS_NEXT_RESOURCE_VALUE        458
#define _APS_NEXT_COMMAND_VALUE         32843
#define _APS_NEXT_CONTROL_VALUE         1156
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
