// Copyleft 2014 Chris Korda
// This program is free software; you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation; either version 2 of the License, or any later version.
/*
        chris korda
 
		revision history:
		rev		date	comments
        00      05apr14	initial version
		01		22apr14	add generic text macros

        MIDI controller names
 
*/

MIDI_CTRLR_NAME(/*   0 */ _T("Bank Select MSB"))
MIDI_CTRLR_NAME(/*   1 */ _T("Modulation Wheel MSB"))
MIDI_CTRLR_NAME(/*   2 */ _T("Breath Controller MSB"))
MIDI_CTRLR_NAME(/*   3 */ NULL)
MIDI_CTRLR_NAME(/*   4 */ _T("Foot Controller MSB"))
MIDI_CTRLR_NAME(/*   5 */ _T("Portamento Time MSB"))
MIDI_CTRLR_NAME(/*   6 */ _T("Data Entry MSB"))
MIDI_CTRLR_NAME(/*   7 */ _T("Volume MSB"))
MIDI_CTRLR_NAME(/*   8 */ _T("Balance MSB"))
MIDI_CTRLR_NAME(/*   9 */ NULL)
MIDI_CTRLR_NAME(/*  10 */ _T("Pan MSB"))
MIDI_CTRLR_NAME(/*  11 */ _T("Expression Controller MSB"))
MIDI_CTRLR_NAME(/*  12 */ _T("Effect Control 1 MSB"))
MIDI_CTRLR_NAME(/*  13 */ _T("Effect Control 2 MSB"))
MIDI_CTRLR_NAME(/*  14 */ NULL)
MIDI_CTRLR_NAME(/*  15 */ NULL)
MIDI_CTRLR_NAME(/*  16 */ _T("General Purpose Controller 1"))
MIDI_CTRLR_NAME(/*  17 */ _T("General Purpose Controller 2"))
MIDI_CTRLR_NAME(/*  18 */ _T("General Purpose Controller 3"))
MIDI_CTRLR_NAME(/*  19 */ _T("General Purpose Controller 4"))
MIDI_CTRLR_NAME(/*  20 */ NULL)
MIDI_CTRLR_NAME(/*  21 */ NULL)
MIDI_CTRLR_NAME(/*  22 */ NULL)
MIDI_CTRLR_NAME(/*  23 */ NULL)
MIDI_CTRLR_NAME(/*  24 */ NULL)
MIDI_CTRLR_NAME(/*  25 */ NULL)
MIDI_CTRLR_NAME(/*  26 */ NULL)
MIDI_CTRLR_NAME(/*  27 */ NULL)
MIDI_CTRLR_NAME(/*  28 */ NULL)
MIDI_CTRLR_NAME(/*  29 */ NULL)
MIDI_CTRLR_NAME(/*  30 */ NULL)
MIDI_CTRLR_NAME(/*  31 */ NULL)
MIDI_CTRLR_NAME(/*  32 */ _T("Bank Select LSB"))
MIDI_CTRLR_NAME(/*  33 */ _T("Modulation Wheel LSB"))
MIDI_CTRLR_NAME(/*  34 */ _T("Breath Controller LSB"))
MIDI_CTRLR_NAME(/*  35 */ NULL)
MIDI_CTRLR_NAME(/*  36 */ _T("Foot Pedal LSB"))
MIDI_CTRLR_NAME(/*  37 */ _T("Portamento Time LSB"))
MIDI_CTRLR_NAME(/*  38 */ _T("Data Entry LSB"))
MIDI_CTRLR_NAME(/*  39 */ _T("Volume LSB"))
MIDI_CTRLR_NAME(/*  40 */ _T("Balance LSB"))
MIDI_CTRLR_NAME(/*  41 */ NULL)
MIDI_CTRLR_NAME(/*  42 */ _T("Pan LSB"))
MIDI_CTRLR_NAME(/*  43 */ _T("Expression LSB"))
MIDI_CTRLR_NAME(/*  44 */ _T("Effect Control 1 LSB"))
MIDI_CTRLR_NAME(/*  45 */ _T("Effect Control 2 LSB"))
MIDI_CTRLR_NAME(/*  46 */ NULL)
MIDI_CTRLR_NAME(/*  47 */ NULL)
MIDI_CTRLR_NAME(/*  48 */ NULL)
MIDI_CTRLR_NAME(/*  49 */ NULL)
MIDI_CTRLR_NAME(/*  50 */ NULL)
MIDI_CTRLR_NAME(/*  51 */ NULL)
MIDI_CTRLR_NAME(/*  52 */ NULL)
MIDI_CTRLR_NAME(/*  53 */ NULL)
MIDI_CTRLR_NAME(/*  54 */ NULL)
MIDI_CTRLR_NAME(/*  55 */ NULL)
MIDI_CTRLR_NAME(/*  56 */ NULL)
MIDI_CTRLR_NAME(/*  57 */ NULL)
MIDI_CTRLR_NAME(/*  58 */ NULL)
MIDI_CTRLR_NAME(/*  59 */ NULL)
MIDI_CTRLR_NAME(/*  60 */ NULL)
MIDI_CTRLR_NAME(/*  61 */ NULL)
MIDI_CTRLR_NAME(/*  62 */ NULL)
MIDI_CTRLR_NAME(/*  63 */ NULL)
MIDI_CTRLR_NAME(/*  64 */ _T("Damper Pedal"))
MIDI_CTRLR_NAME(/*  65 */ _T("Portamento"))
MIDI_CTRLR_NAME(/*  66 */ _T("Sustenuto Pedal"))
MIDI_CTRLR_NAME(/*  67 */ _T("Soft Pedal"))
MIDI_CTRLR_NAME(/*  68 */ _T("Legato Pedal"))
MIDI_CTRLR_NAME(/*  69 */ _T("Hold 2 Pedal"))
MIDI_CTRLR_NAME(/*  70 */ _T("Sound Variation"))
MIDI_CTRLR_NAME(/*  71 */ _T("Sound Timbre"))
MIDI_CTRLR_NAME(/*  72 */ _T("Sound Release Time"))
MIDI_CTRLR_NAME(/*  73 */ _T("Sound Attack Time"))
MIDI_CTRLR_NAME(/*  74 */ _T("Sound Brightness"))
MIDI_CTRLR_NAME(/*  75 */ _T("Sound Control 6"))
MIDI_CTRLR_NAME(/*  76 */ _T("Sound Control 7"))
MIDI_CTRLR_NAME(/*  77 */ _T("Sound Control 8"))
MIDI_CTRLR_NAME(/*  78 */ _T("Sound Control 9"))
MIDI_CTRLR_NAME(/*  79 */ _T("Sound Control 10"))
MIDI_CTRLR_NAME(/*  80 */ _T("General Purpose Button 1"))
MIDI_CTRLR_NAME(/*  81 */ _T("General Purpose Button 2"))
MIDI_CTRLR_NAME(/*  82 */ _T("General Purpose Button 3"))
MIDI_CTRLR_NAME(/*  83 */ _T("General Purpose Button 4"))
MIDI_CTRLR_NAME(/*  84 */ NULL)
MIDI_CTRLR_NAME(/*  85 */ NULL)
MIDI_CTRLR_NAME(/*  86 */ NULL)
MIDI_CTRLR_NAME(/*  87 */ NULL)
MIDI_CTRLR_NAME(/*  88 */ NULL)
MIDI_CTRLR_NAME(/*  89 */ NULL)
MIDI_CTRLR_NAME(/*  90 */ NULL)
MIDI_CTRLR_NAME(/*  91 */ _T("Reverb Level"))
MIDI_CTRLR_NAME(/*  92 */ _T("Tremolo Level"))
MIDI_CTRLR_NAME(/*  93 */ _T("Chorus Level"))
MIDI_CTRLR_NAME(/*  94 */ _T("Celeste Level"))
MIDI_CTRLR_NAME(/*  95 */ _T("Phaser Level"))
MIDI_CTRLR_NAME(/*  96 */ _T("Data Increment"))
MIDI_CTRLR_NAME(/*  97 */ _T("Data Decrement"))
MIDI_CTRLR_NAME(/*  98 */ _T("Non-registered Parameter LSB"))
MIDI_CTRLR_NAME(/*  99 */ _T("Non-registered Parameter MSB"))
MIDI_CTRLR_NAME(/* 100 */ _T("Registered Parameter LSB"))
MIDI_CTRLR_NAME(/* 101 */ _T("Registered Parameter MSB"))
MIDI_CTRLR_NAME(/* 102 */ NULL)
MIDI_CTRLR_NAME(/* 103 */ NULL)
MIDI_CTRLR_NAME(/* 104 */ NULL)
MIDI_CTRLR_NAME(/* 105 */ NULL)
MIDI_CTRLR_NAME(/* 106 */ NULL)
MIDI_CTRLR_NAME(/* 107 */ NULL)
MIDI_CTRLR_NAME(/* 108 */ NULL)
MIDI_CTRLR_NAME(/* 109 */ NULL)
MIDI_CTRLR_NAME(/* 110 */ NULL)
MIDI_CTRLR_NAME(/* 111 */ NULL)
MIDI_CTRLR_NAME(/* 112 */ NULL)
MIDI_CTRLR_NAME(/* 113 */ NULL)
MIDI_CTRLR_NAME(/* 114 */ NULL)
MIDI_CTRLR_NAME(/* 115 */ NULL)
MIDI_CTRLR_NAME(/* 116 */ NULL)
MIDI_CTRLR_NAME(/* 117 */ NULL)
MIDI_CTRLR_NAME(/* 118 */ NULL)
MIDI_CTRLR_NAME(/* 119 */ NULL)
MIDI_CTRLR_NAME(/* 120 */ _T("All Sound Off"))
MIDI_CTRLR_NAME(/* 121 */ _T("All Controllers Off"))
MIDI_CTRLR_NAME(/* 122 */ _T("Local Control"))
MIDI_CTRLR_NAME(/* 123 */ _T("All Notes Off"))
MIDI_CTRLR_NAME(/* 124 */ _T("Omni Mode Off"))
MIDI_CTRLR_NAME(/* 125 */ _T("Omni Mode On"))
MIDI_CTRLR_NAME(/* 126 */ _T("Mono Operation"))
MIDI_CTRLR_NAME(/* 127 */ _T("Poly Operation"))

#undef MIDI_CTRLR_NAME
